# Generated by Django 2.2 on 2019-09-17 04:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='城市名称')),
                ('describe', models.CharField(max_length=200, verbose_name='描述')),
            ],
            options={
                'verbose_name': '城市',
                'verbose_name_plural': '城市',
            },
        ),
        migrations.CreateModel(
            name='CourseOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=50, verbose_name='机构名称')),
                ('describe', models.TextField(verbose_name='相关描述')),
                ('category', models.CharField(choices=[('PXJG', '培训机构'), ('GR', '个人'), ('GX', '高校')], default='PXJG', max_length=20, verbose_name='机构类别')),
                ('tag', models.CharField(default='全国知名', max_length=10, verbose_name='机构标签')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('address', models.CharField(max_length=200, verbose_name='机构地址')),
                ('image', models.ImageField(blank=True, null=True, upload_to='org/%Y/%m', verbose_name='logo')),
                ('students', models.IntegerField(default=0, verbose_name='学习人数')),
                ('course_nums', models.IntegerField(default=0, verbose_name='课程数')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.City', verbose_name='所在城市')),
            ],
            options={
                'verbose_name': '培训机构',
                'verbose_name_plural': '培训机构',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('name', models.CharField(max_length=20, verbose_name='讲师名称')),
                ('worke_position', models.CharField(max_length=50, verbose_name='工作职位')),
                ('worke_company', models.CharField(max_length=50, verbose_name='就职公司')),
                ('worke_years', models.IntegerField(verbose_name='工作年限')),
                ('points', models.CharField(max_length=100, verbose_name='教学特点')),
                ('click_nums', models.IntegerField(default=0, verbose_name='点击量')),
                ('fav_nums', models.IntegerField(default=0, verbose_name='收藏人数')),
                ('age', models.IntegerField(verbose_name='讲师年龄')),
                ('image', models.ImageField(upload_to='teacher/%Y/%m', verbose_name='头像图')),
                ('courseOrg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.CourseOrg', verbose_name='所属机构')),
            ],
            options={
                'verbose_name': '讲师',
                'verbose_name_plural': '讲师',
            },
        ),
    ]
